### PR TITLE
Create form for new Trips

### PR DESCRIPTION
**Pull request by JSchindler21**
- create Form for new Trips
- card is displayed under the Form and on the Secret Places Page 
- Delete Button for the own Cards
- final styling

### CODE REVIEW

**Review by matthias-grgic — COMMENTED** [review]
doesnt work for me yet, cant add any new trips.
filled out everything and I still receive the message: "please fill out all input fields !".

**Comment by JSchindler21** [comment]
please, check again... i guess it is the validation, i changed it first ( I'll work it into it when I have time). thanks

**Comment by matthias-grgic** [comment]
still not working, same message as before.

**Comment by JSchindler21** [comment]
sorry for that, it should work...it works for me...did you enter something everywhere? also for profile photo and inspiration photo a photo with a url (at the moment this is only possible with a url ) ?

**Comment by matthias-grgic** [comment]
hmm i did, so here is what i typed:
[](url
Bildschirmfoto von 2022-02-03 22-28-26
)

**Pull request closed without merging**
